
services:
  vue-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://resume-backend:8006/api}
    container_name: resume-frontend
    ports:
      - "3000:3000"
    networks:
      - resume-app-network
    restart: always

networks:
  resume-app-network:
    external: true
    name: resume-app-network